### ISSUE TITLE
Launch the player directly with an MP3 file

### ISSUE THREAD

**Issue by TimberlAndRE-de** [mp3chapters/mp3chapters-player#3]
Is it possible to launch this awesome player directly with an mp3 file?
Maybe by calling it with a startup parameter like "MP3 Chapter Player.exe" -f "c:\path\to\file.mp3"

I use the player to listen to podcasts on my Win PC. I have another program to download/organize my podcasts, but I can specify an external player there. So I just need to be able to pass the MP3 file directly to MP3 Chapter Player so that it starts directly.

**Comment by DominikPeters** [comment]
Nice idea! Can you try version 0.3.0? Without the `-f`; there might be a difference whether the file is in a standard directory like under Downloads or Documents or in some weird directory (in which case it might not load).

**Comment by TimberlAndRE-de** [comment]
oh wow! you're fast, thank you so much.

I tried the windows setup ( MP3.Chapter.Player_0.3.0_x64-setup.exe ) but unfortunately it doesn't seem to work.
If I launch it like "MP3 Chapter Player.exe" "R:\podcast.mp3", the program opens but no mp3 is loaded.
And I can't open files anymore. When I chose "Open" from the menu simply nothing happens (the file dialog is not showing?)
(I reinstalled v0.2.0 to make sure it's not something weird on my system but the old version works, open file dialog is popping up)

**Comment by DominikPeters** [comment]
Oops, thanks for testing. Does it work in 0.3.1?

**Comment by TimberlAndRE-de** [comment]
Yes, now I can open files with the file dialog again. 💯 
But the command line call is still not working.

`"MP3 Chapter Player.exe" "R:\podcast.mp3"`
opens the program window (and sets the correct window title "podcast.mp3") but no file gets loaded.

![grafik](https://github.com/user-attachments/assets/260c76d5-1efc-4475-a453-01351cb68d34)

**Comment by DominikPeters** [comment]
I see. Does it work if you place the file in the "My Documents" folder? There is some weird permissions problem, not sure if I can get around it.

**Comment by TimberlAndRE-de** [comment]
Yes, you're right. It works from the "My Documents" folder.
So sad that it doesn't work out. Unfortunately, I can't save my files in the Documents folder.
But thank you in any case for your help and efforts!
